# Site settings
title: BinaryBlitz
email: job@binaryblitz.ru
description: > # this means to ignore newlines until "baseurl:"
  Мы – команда специалистов и программных инженеров, которая
  занимается разработкой мобильных приложений, серверов и веб-сайтов.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://binaryblitz.ru" # the base hostname & protocol for your site

# User setting
owner:
email: info@binaryblitz.ru
facebook_username:
twitter_username:
github_username:
address:
  - line: "Г. Москва"
  - line: "ул. Большая никитская д. 22/2"
  # Feel free to add more lines here
telephone: +7-968-45-25-493
copyright: BinaryBlitz

# API settings
google_api_key: AIzaSyDl18tfqtlhHH4ZH58WclCvtAdWZqtV7JI

# Build settings
markdown: kramdown