# Site settings
title: BinaryBlitz
email: job@binaryblitz.ru
description: > # this means to ignore newlines until "baseurl:"
  Мы – команда специалистов и программных инженеров, которая
  занимается разработкой мобильных приложений, серверов и веб-сайтов.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://binaryblitz.ru" # the base hostname & protocol for your site

# User setting
owner:
email: info@binaryblitz.ru
facebook_username:
twitter_username:
github_username:
address:
  - line: "ул. Большая Никитская д. 22"
  - line: "Москва"
  # Feel free to add more lines here
telephone: +7 (985) 555-88-60
copyright: BinaryBlitz

# API settings
google_api_key: AIzaSyDl18tfqtlhHH4ZH58WclCvtAdWZqtV7JI

# Build settings
markdown: kramdown
